// <auto-generated />
using System;
using Laboratorio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laboratorio.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902162726_AgregarCamposDescuentoFactura")]
    partial class AgregarCamposDescuentoFactura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laboratorio.Api.Models.ExamenCatalogo", b =>
                {
                    b.Property<Guid>("ExamenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsTercerizado")
                        .HasColumnType("boolean");

                    b.Property<string>("LaboratorioDestino")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreParametro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RangoReferenciaDefecto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TecnicaDefecto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unidades")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ExamenId");

                    b.HasIndex("TenantId");

                    b.ToTable("Examenes_Catalogo");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Factura", b =>
                {
                    b.Property<Guid>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DescuentoAplicadoPor")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DescuentoAutorizadoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaDescuento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoDescuento")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrdenLaboratorioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TasaCambio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FacturaId");

                    b.HasIndex("OrdenLaboratorioId");

                    b.HasIndex("TenantId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.OrdenLaboratorio", b =>
                {
                    b.Property<Guid>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrelativoDiario")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaValidacionFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoExamen")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ObservacionBioanalista")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PermitirEnvioParcial")
                        .HasColumnType("boolean");

                    b.Property<string>("RutaArchivoExterno")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("OrdenId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TenantId");

                    b.ToTable("Ordenes_Laboratorio");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Paciente", b =>
                {
                    b.Property<Guid>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroHistoria")
                        .HasColumnType("text");

                    b.Property<string>("NumeroHistoriaFisica")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("TelefonoPrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelefonoRepresentante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PacienteId");

                    b.HasIndex("TenantId", "Cedula")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Pago", b =>
                {
                    b.Property<Guid>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("PagoId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("TenantId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.ResultadoDetalle", b =>
                {
                    b.Property<Guid>("ResultadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoTercerizado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ExamenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FueraDeRango")
                        .HasColumnType("boolean");

                    b.Property<bool>("MuestraEntregada")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrdenId")
                        .HasColumnType("uuid");

                    b.Property<string>("RangoReferenciaAplicado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TecnicaAplicada")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UuidBioanalista")
                        .HasColumnType("uuid");

                    b.Property<string>("ValorResultado")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ResultadoId");

                    b.HasIndex("ExamenId");

                    b.HasIndex("OrdenId");

                    b.ToTable("Resultados_Detalle");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreClinica")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Rif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinAutorizacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId");

                    b.HasIndex("TenantId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.ExamenCatalogo", b =>
                {
                    b.HasOne("Laboratorio.Api.Models.Tenant", "Tenant")
                        .WithMany("Examenes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Factura", b =>
                {
                    b.HasOne("Laboratorio.Api.Models.OrdenLaboratorio", "OrdenLaboratorio")
                        .WithMany()
                        .HasForeignKey("OrdenLaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Laboratorio.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenLaboratorio");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.OrdenLaboratorio", b =>
                {
                    b.HasOne("Laboratorio.Api.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Laboratorio.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Paciente", b =>
                {
                    b.HasOne("Laboratorio.Api.Models.Tenant", "Tenant")
                        .WithMany("Pacientes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Pago", b =>
                {
                    b.HasOne("Laboratorio.Api.Models.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Laboratorio.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.ResultadoDetalle", b =>
                {
                    b.HasOne("Laboratorio.Api.Models.ExamenCatalogo", "Examen")
                        .WithMany()
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Laboratorio.Api.Models.OrdenLaboratorio", "Orden")
                        .WithMany("Resultados")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examen");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Usuario", b =>
                {
                    b.HasOne("Laboratorio.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Factura", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.OrdenLaboratorio", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("Laboratorio.Api.Models.Tenant", b =>
                {
                    b.Navigation("Examenes");

                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
